[package]
name = "integration_tests_core"
version = "0.1.0"
edition = "2024"
license.workspace = true

# [[test]]
# name = "integration_tests_core"

[dependencies]
# Workspace dependencies (sorted)
chat-sqlite = { workspace = true }
components = { workspace = true }
crypto = { workspace = true }
libchat = { workspace = true }
shared-traits = { workspace = true }

# External dependencies (sorted)
tracing = "0.1"

[dev-dependencies]
chat-proto = { workspace = true }
chat-sqlite = { workspace = true }
de-mls = { workspace = true }
storage = { workspace = true }

# External dependencies (sorted)
prost = "0.14.1"
tempfile = "3"
tracing = "0.1.44"
tracing-subscriber = "0.3"
