use prost::Message;

// Generated by prost-build
// mod inbox {
//     pub mod v1 {
//         include!(concat!(env!("OUT_DIR"), "/logoschat.inbox.rs"));
//     }
// }

// use chat::v1::InboxV1Frame;

fn main() {
    // // Create message
    // let msg = InboxV1Frame {
    //     recipient: "Recipient",
    // };

    // // Serialize
    // let bytes = msg.encode_to_vec();
    // println!("Encoded: {} bytes", bytes.len());

    // // Deserialize
    // let decoded = TextMessage::decode(&bytes[..]).unwrap();
    // println!("Content: {}", decoded.content);
}
